pixelpics/pixelfy_app/urls.py
from django.urls import path
from . import views

app_name = 'pixelfy'  # for namespacing
urlpatterns = [
    path('', views.index, name='index'),
    path('like_post/<int:pk>/', views.like_post, name='like_post'),
    path('feed/best', views.index_best, name='best'),
    path('feed/year', views.index_year, name='year'),
    path('feed/month', views.index_month, name='month'),
    path('feed/week', views.index_week, name='week'),
    path('feed/day', views.index_day, name='day'),
    path('feed/<user>', views.index_user, name='user'),
    path('profile/upload/', views.upload, name='upload'),
]

pixelpics/pixelpics/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pixelfy_app.urls')),  # Note: all your app urls will start with this path
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', views.register, name='register'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/profile/delete/<int:pk>/', views.delete_post, name='delete_post'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pixelpics/pixelfy_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings


# Create your models here.
class Pixelfy(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    original_image = models.ImageField(upload_to='images/original')
    altered_image = models.ImageField(upload_to='images/altered')
    created_date = models.DateTimeField(default=timezone.now)
    # public = models.BooleanField(default=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    def __str__(self):
        return self.user.username + str(self.pk)

    def total_likes(self):
        return self.likes.count()

pixelpics/pixelfy_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.files.base import ContentFile
from django.template.loader import render_to_string
from base64 import b64decode
from .models import *
from datetime import *


# Create your views here.
def index(request):
    feed = Pixelfy.objects.all().order_by('-created_date')
    liked = [post for post in feed if post.likes.filter(id=request.user.id).exists()]
    return render(request, 'pixelfy_app/index.html', {'posts': feed, 'liked': liked})


def index_user(request, user):
    feed = Pixelfy.objects.filter(user__username=user).order_by('-created_date')
    liked = [post for post in feed if post.likes.filter(id=request.user.id).exists()]
    return render(request, 'pixelfy_app/index.html', {'posts': feed, 'liked': liked})


def index_best(request):
    feed = Pixelfy.objects.annotate(like_count=Count('likes')).order_by('-like_count')
    liked = [post for post in feed if post.likes.filter(id=request.user.id).exists()]
    return render(request, 'pixelfy_app/index.html', {'posts': feed, 'liked': liked})


def index_year(request):
    current = datetime.now()
    last_year = current - timedelta(days=365)
    feed = Pixelfy.objects.filter(created_date__gte=last_year).order_by('-created_date')
    liked = [post for post in feed if post.likes.filter(id=request.user.id).exists()]
    return render(request, 'pixelfy_app/index.html', {'posts': feed, 'liked': liked})


def index_month(request):
    current = datetime.now()
    last_month = current - timedelta(days=30)
    feed = Pixelfy.objects.filter(created_date__gte=last_month).order_by('-created_date')
    liked = [post for post in feed if post.likes.filter(id=request.user.id).exists()]
    return render(request, 'pixelfy_app/index.html', {'posts': feed, 'liked': liked})


def index_week(request):
    current = datetime.now()
    last_week = current - timedelta(days=7)
    feed = Pixelfy.objects.filter(created_date__gte=last_week).order_by('-created_date')
    liked = [post for post in feed if post.likes.filter(id=request.user.id).exists()]
    return render(request, 'pixelfy_app/index.html', {'posts': feed, 'liked': liked})


def index_day(request):
    current = datetime.now()
    last_day = current - timedelta(days=1)
    feed = Pixelfy.objects.filter(created_date__gte=last_day).order_by('-created_date')
    liked = [post for post in feed if post.likes.filter(id=request.user.id).exists()]
    return render(request, 'pixelfy_app/index.html', {'posts': feed, 'liked': liked})


@login_required
def upload(request):
    if request.method == "POST":
        original = request.FILES['original_image']
        ext, altered_b64 = request.POST['altered_image'].split(';base64,')
        ext = ext.split('/')[-1]
        altered = ContentFile(b64decode(altered_b64), name='temp.' + ext)  # You can save this as file instance.
        post = Pixelfy(user=request.user, original_image=original, altered_image=altered)
        post.save()
        return redirect('profile')
    return render(request, 'pixelfy_app/upload.html')


def alt_filename(request):
    pass


def like_post(request):
    post = get_object_or_404(Pixelfy, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
    }
    if request.is_ajax():
        html = render_to_string('pixelfy:like_section.html', context, request=request)
        return JsonResponse({'form': html})

pixelpics/pixelpics/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from pixelfy_app.models import *


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            username = user.username
            password = request.POST['password1']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('pixelfy:index')  # TODO redirect to profile?

    form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def profile(request):
    gallery = Pixelfy.objects.filter(user=request.user).order_by('-created_date')
    return render(request, 'registration/profile.html', {'gallery': gallery})


@login_required
def delete_post(request, pk):
    post = get_object_or_404(Pixelfy, pk=pk, user=request.user)
    post.delete()
    return redirect('profile')

pixelpics/pixelfy_app/templates/pixelfy_app/base.html
{% load static %}<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}PixelPics{% endblock title %}</title>
    {% block main_styles %}
        <link rel="stylesheet" href="https://bootswatch.com/4/cyborg/bootstrap.min.css">
        <link rel='stylesheet' href='{% static "css/feed.css" %}'>
    {% endblock %}

    {% block extra_styles %}
    {% endblock %}

    {% block js_head %}
    {% endblock %}
</head>
<body>
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark mb-5">
        <div class="container">
            <a class="navbar-brand" href="{% url 'pixelfy:index' %}">PixelPics</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                      <a href="{% url 'pixelfy:upload' %}">
                        <button type="button" class="btn btn-success">Pixelfy Image</button>
                      </a>
                    </li>
                    <li class="nav-item">
                        <a class='nav-link' href="{% url 'pixelfy:index' %}">Feed</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle" href="#" id="user" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hello {{user.username}}
                            <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="user">
                             <!-- pk=user.pk  -->
                            <a class="dropdown-item" href="{% url 'profile'%}">My Collection</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class='nav-link' href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class='nav-link' href="{% url 'register' %}">Register</a>
                    </li>
                    {% endif %}
              </ul>
            </div>
        </div>
    </div>
    <div class='page-content'>
    {% block content %}
    {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    {% block js_body %}
    {% endblock %}
</body>
</html>

pixelpics/pixelfy_app/templates/pixelfy_app/index.html
{% extends 'pixelfy_app/base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="feed-header col-8 d-flex justify-content-around">
                <a class="feed" href="{% url 'pixelfy:best' %}"><h5>Most liked</h5></a>
                <a class="feed" href="{% url 'pixelfy:year' %}"><h5>Year</h5></a>
                <a class="feed" href="{% url 'pixelfy:month' %}"><h5>Month</h5></a>
                <a class="feed" href="{% url 'pixelfy:week' %}"><h5>Week</h5></a>
                <a class="feed" href="{% url 'pixelfy:day' %}"><h5>Day</h5></a>
            </div>
        </div>
    {% for post in posts %}
        <div class="row mb-3">
            <!-- <div class="col-sm-2"></div> -->
            <div class="col-sm-12">
                <div class="feed-topper break d-flex justify-content-between">
                    <div><a href="{% url 'pixelfy:user' user=post.user %}" class=""><h5 class="card-title">{{post.user}}</h5></a></div>
                    <div class="d-flex align-items-center">
                        <div id="like-section">
                            {% include 'pixelfy_app/like_section.html' %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <img class="img-feed" src="{{post.original_image.url}}" alt="Card image cap">
                    </div>
                    <div class="col-6">
                        <img class="img-feed" src="{{post.altered_image.url}}" alt="Card image cap">
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>


{% endblock %}

{% block js_body %}
  <script src="{% static 'js/feed.js' %}"></script>
{% endblock %}

pixelpics/pixelfy_app/templates/pixelfy_app/like_section.html
{{ post.likes.count }} Like{{ post.likes.count|pluralize }}
{% if request.user.is_authenticated %}
<form action="{% url 'pixelfy:like_post' %}" method='post'>
    {% csrf_token %}
    {% if is_liked %}
        <button type="submit" id='like' name="post_id" value="{{ post.id }}" class="btn btn-sm btn-danger">Dislike</button>
    {% else %}
        <button type="submit" id='like' name="post_id" value="{{ post.id }}" class="btn btn-sm btn-info">Like</button>
    {% endif %}
</form>
{% endif %}

pixelpics/pixelfy_app/templates/pixelfy_app/upload.html
{% extends 'pixelfy_app/base.html' %}
{% load static %}

{% block extra_styles %}
    <link rel='stylesheet' href='{% static "css/pixelfy.css" %}'>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 m-auto">
            <div class="custom-file mb-3">
                <input type="file" class="custom-file-input" id="upload-file"/>
                <label for="upload-file" class="custom-file-label">Choose Image</label>
            </div>

            <div class="row">
                <div class="col-md-9">
                    <canvas id="canvas"></canvas>
                </div>
                <div class="col-md-3">
                    <div>
                        <button id="pixelate-btn" class="filter-btn pixelate-add btn btn-info btn-block">Pixelfy</button>
                        <input type="range" class="custom-range" min="20" max="180" step="1" value="100" id="pixelsize">
                    </div>
                    <div>
                        <button id="mixelate-btn" class="filter-btn pixelate-add btn btn-info btn-block">Random Noise</button>
                        <input type="range" class="custom-range" min="20" max="180" step="1" value="100" id="mixelsize">
                    </div>
                </div>
            </div>

            <h4 class="text-center my-3">Effects</h4>

            <div class="row text-center my-4">
                <div class="col-md-3">
                    <div class="btn-group btn-group-md">
                        <button class="filter-btn brightness-remove btn btn-info">-</button>
                        <button class="btn btn-secondary btn-disabled" disabled>Brightness</button>
                        <button class="filter-btn brightness-add btn btn-info">+</button>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="btn-group btn-group-md">
                        <button class="filter-btn contrast-remove btn btn-info">-</button>
                        <button class="btn btn-secondary btn-disabled" disabled>Contrast</button>
                        <button class="filter-btn contrast-add btn btn-info">+</button>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="btn-group btn-group-md">
                        <button class="filter-btn saturation-remove btn btn-info">-</button>
                        <button class="btn btn-secondary btn-disabled" disabled>Saturation</button>
                        <button class="filter-btn saturation-add btn btn-info">+</button>
                    </div>
                </div>

                    <div class="col-md-3">
                        <div class="btn-group btn-group-md">
                            <button class="filter-btn vibrance-remove btn btn-info">-</button>
                            <button class="btn btn-secondary btn-disabled" disabled>Vibrance</button>
                            <button class="filter-btn vibrance-add btn btn-info">+</button>
                        </div>
                    </div>
                </div>

                <h4 class="text-center my-3">Filters</h4>

                <div class="row mb-3">
                    <div class="col-md-3">
                        <button class="filter-btn vintage-add btn btn-dark btn-block">Vintage</button>
                    </div>

                    <div class="col-md-3">
                        <button class="filter-btn lomo-add btn btn-dark btn-block">Lomo</button>
                    </div>

                    <div class="col-md-3">
                        <button class="filter-btn clarity-add btn btn-dark btn-block">Clarity</button>
                    </div>

                    <div class="col-md-3">
                        <button class="filter-btn sincity-add btn btn-dark btn-block">Sin City</button>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-3">
                        <button class="filter-btn crossprocess-add btn btn-dark btn-block">Cross Process</button>
                    </div>

                    <div class="col-md-3">
                        <button class="filter-btn pinhole-add btn btn-dark btn-block">Pinhole</button>
                    </div>

                    <div class="col-md-3">
                        <button class="filter-btn nostalgia-add btn btn-dark btn-block">Nostalgia</button>
                    </div>

                    <div class="col-md-3">
                        <button class="filter-btn hermajesty-add btn btn-dark btn-block">Her Majesty</button>
                    </div>
                </div>

                <div class="row my-5">
                    <div class="col-md-6">
                       <button id="download-btn" class="btn btn-primary btn-block">Save & Download Image</button>
                    </div>

                    <div class="col-md-6">
                       <button id="revert-btn" class="btn btn-danger btn-block">Remove Filters</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js_body %}
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/camanjs/4.1.2/caman.full.min.js"></script>
    <script src="{% static 'js/upload.js' %}"></script>
{% endblock %}